Remove Slashes from Datalog vars
dvargas92495/roamjs-query-builder pull request #56
Opened 2023-04-07 06:08 UTC by dvargas92495

2023-04-07 06:08 UTC, dvargas92495 commented on src/utils/compileDatalog.ts
> +const toVar = (v = "undefined") => v.replace(/[\s"()[\]{}/\\]/g, "");
can you pull and verify it this works for those queries?

2023-04-07 06:44 UTC, mdroidian requested changes
`Unmatched delimiter ].`

2023-04-07 14:09 UTC, dvargas92495 commented
Can you paste in the query that's resulting in that error? I'm failing to repro

2023-04-07 18:49 UTC, mdroidian commented
```
Find node Where
node is a Question
```

```
[:find
  (pull ?node [:block/string :node/title :block/uid])
  (pull ?node [:block/uid])
:where
  [(re-pattern "^\\[\\[QUE\\]\\] - (.*?)$") ?/^\\QUE\\-.*?$/-regex]
  [?node :node/title ?node-Title]
  [(re-find ?/^\\QUE\\-.*?$/-regex ?node-Title)]
]
```

2023-04-07 18:56 UTC, mdroidian commented
Sorry, posted wrong query.  Edited previous comment.

2023-04-07 20:29 UTC, dvargas92495 commented
The problem seems to be in the string, not the getVar function. Namely:

`"^\\[\\[QUE\\]\\] - (.*?)$"`

should be

`"^\\\\[\\\\[QUE\\\\]\\\\] - (.*?)$"`

2023-04-07 20:32 UTC, dvargas92495 commented
Is it not hitting this replace? https://github.com/dvargas92495/roamjs-query-builder/blob/SLASHES/src/utils/conditionToDatalog.ts#L86

2023-04-07 23:30 UTC, mdroidian commented
Sorry, I can't seem to test it right now.  I'm having some weird issue.

Whenever I load query builder extension via `Developer Extensions` I'm was getting multiple of the following error:
`ERROR in load-extension: invalid ext-id:  null`

I loaded up a new graph and get this error:
`app-graph.js:68 Uncaught (in promise) Error: Can not register `navigator` for `core` since `navigator` already exists in the prototype and can not be overridden`

And Chrome doesn't register query builder in sources
![image](https://user-images.githubusercontent.com/3792666/230691814-b4af4e8a-9444-44f5-af2a-28a107faf412.png)

I've tried your branch, my fork, and an old commit on my fork. 🤷‍♂️

To top it off, our power it out, so my laptop is about to die. 😣

2023-04-07 23:43 UTC, mdroidian commented
running `npx roamjs-scripts dev --depot` instead of `npm start` seemed to do it

2023-04-07 23:49 UTC, mdroidian commented
> Is it not hitting this replace? https://github.com/dvargas92495/roamjs-query-builder/blob/SLASHES/src/utils/conditionToDatalog.ts#L86

I believe it is hitting it
![image](https://user-images.githubusercontent.com/3792666/230692984-c09e101a-6500-419e-84e4-516280b6564c.png)

2023-04-08 15:59 UTC, dvargas92495 commented
Ok I was able to reproduce both issues:
- delimiter was solved by adding the `^` to the exclusion regex
- build issue solved by bumping up roamjs-scripts to latest

2023-04-08 20:53 UTC, mdroidian approved these changes

2023-04-08 20:54 UTC, merged